- id: doi:10.1073/pnas.2402352121
  type: paper
  description: We isolated a bacterial strain from the host and provided it as a dietary supplement. The treatment changed the microbiota and increased the weight of individuals with low microbiota diversity. This provides direct evidence of the role of the microbiota in the ecology and evolution of natural populations and suggests that the strain we isolated has probiotic potential.
  date: 2024-10-14
  image: images/pnas.jpg
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/shan-e-s/NativeStrain
  tags:
    - collaboration
  repo: 

  - id: doi:10.1016/j.cub.2024.06.029
  type: paper
  description: Automated feeders with custom-built programs allowed for experimental manipulation of spatiotemporal experiences on an individual-level basis. In the what-where-when memory experiment, after learning individualized temporal feeder rules, the birds demonstrated their ability to recall the “what” (food type), “where” (feeder location), and “when” (time since their initial visit of the day) of previous foraging experiences. In the incidental encoding experiment, the birds showed that they were able to encode and recall incidental spatial information regarding previous foraging experiences.
  date: 2024-10-14
  image: images/episodic_like_memory.jpg
  buttons:
  tags:   
  repo: 

- id: doi:10.1093/ismejo/wrae078
  type: paper
  description: Here, we provide experimental evidence from aquatic pond snails (*Lymnaea stagnalis*) that environmental stressors and the gut microbiota explain host phenotypic plasticity and disrupted covariation among traits.
  date: 2024-10-14
  image: images/snail_figure.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/DrGLDavidson/lymnaeastagnalis-microbiome
  tags:
    - collaboration
    - open science
  repo: 


