
- id: doi:10.1073/pnas.2402352121
  image: images/pnas.jpg

- id: doi:10.1099/acmi.0.000910.v1
  image: images/krakenplot.png

- id: doi:10.1101/2023.12.05.569701
  image: images/troisi_2025.jpg

- doi: doi:10.1093/ismejo/wrae078
  image: images/snailfigure.jpg
  title:'Antibiotic-altered gut microbiota explain host memory plasticity and disrupt pace-of-life covariation for an aquatic snail'
  authors:
  - Gabrielle L. Davidson
  - Ignacio A Cienfuego
  - Sarah Dalesman
  link: /https://academic.oup.com/ismej/article/18/1/wrae078/7683888
  publisher: The Multidisciplinary Journal of Microbial Ecology
  date: '2024-05-30'
  
- id: doi:10.1111/mec.16919
  image: images/somers_2023.jpg

- id: doi:10.1111/jav.02894
  image: images/delahera_2023.jpg

- id: doi:10.1016/j.anbehav.2022.02.007
  image: images/davidson_2022.jpg

- id: doi:10.1111/1365-2656.13600
  image: images/coomes_2022.jpg

- id: doi:10.1111/1365-2656.13551
  image: images/reichert_2021.jpg

- id: doi:10.1101/2021.04.28.441816
  image: images/reichert_2021b.png

- id: doi:10.1111/1365-2656.13428
  image: images/davidson_2021.jpg

- id: doi:10.1016/j.anbehav.2021.01.024
  image: images/cooke_2020.jpg

- id: doi:10.1101/2020.12.16.423008
  image: images/coomes_2022.jpg

- id: doi:10.1016/j.tree.2020.06.014
  image: images/davidson_2020b.png

- id: doi:10.1098/rsos.192107
  image: images/reichert_2020.jpg

- id: doi:10.1098/rstb.2017.0286
  image: images/davidson_2018.jpg

- id: doi:10.11646/zoosymposia.12.1.6
  image: images/helden_2018.jpg

- id: doi:10.1098/rsos.172218
  image: images/davidson_2018b.png

- id: doi:10.1098/rsbl.2016.0783
  image: images/davidson_2017b.jpg

- doi: doi:10.1038/srep40062
  image: images/davidson_2017.png
  title: 'The development of support intuitions and object causality in juvenile Eurasian jays (Garrulus glandarius)'
  authors:
  - Gabrielle L. Davidson
  - Rachael Miller
  - Elsa Loissel
  - Lucy G. Cheke
  - Nicola S. Clayton
  link: https://www.nature.com/articles/srep40062
  publisher: Scientific Reports
  date: '2017-02-24'

- id: doi:10.1016/j.anbehav.2015.07.010
  image: images/davidson_2015.jpg

- id: doi:10.1098/rsbl.2013.1077
  image: images/davidson_2014.jpg

- id: doi:10.1016/j.anbehav.2013.10.024
  image: images/davidson_2013.jpg

- id: doi:10.1136/jnnp-2012-302451
  image: images/murphy_2012.jpg

- id: doi:10.1007/s00415-011-6397-y
  image: images/davidson_2012.png

- id: doi:10.1111/j.1529-8027.2012.00400.x
  image: images/rossor.jpg

- id: doi:10.1136/jnnp.2010.228965
  image: images/murphy_2010.jpg