- id: doi.org/10.1002/ece3.71565
  image: images/coomes_2025.jpg

- id: doi:10.1099/acmi.0.000910.v2
  image: images/krakenplot.png

- id: doi:10.1073/pnas.2402352121
  image: images/pnas.jpg

- doi: doi:10.1016/j.cub.2024.06.029
  image: images/episodiclikememory.jpg
  title: 'Episodic-like memory in wild free-living blue tits and great tits'
  authors:
  - James Davies
  - Nicky S. Clayton
  - Gabrielle L. Davidson
  link: https://linkinghub.elsevier.com/retrieve/pii/S0960-9822(24)00813-3
  publisher: Current Biology
  date: '2024-08-24'

- id: doi:10.1099/acmi.0.000910.v1
  remove: true

- doi: doi:10.1017/S0959270924000133
  image: images/gough_2024.png
  title: 'Modelling habitat suitability for the Critically Endangered Manumea or Tooth-billed Pigeon Didunculus strigirostris using past and present baselines'
  authors:
  - William B. Gough
  - Michael A. Hudson
  - H. Glyn Young
  - Joe Wood
  - Hester Whitehead
  - Samuel T. Turvey
  link: https://www.cambridge.org/core/journals/bird-conservation-international/article/modelling-habitat-suitability-for-the-critically-endangered-manumea-or-toothbilled-pigeon-didunculus-strigirostris-using-past-and-present-baselines/8262C1512201EE1712A3280D4CA3CFC0#access-block
  publisher: Bird Conservation International
  date: '2024-09-18'

- id: doi:10.1101/2023.12.05.569701
  image: images/troisi_2025.jpg

- id: doi:10.1093/ismejo/wrae078
  image: images/snailfigure.jpg
  
- id: doi:10.1111/mec.16919
  image: images/somers_2023.jpg

- id: doi:10.1111/jav.02894
  image: images/delahera_2023.jpg

- id: doi:10.1016/j.anbehav.2022.02.007
  image: images/davidson_2022.jpg

- id: doi:10.1111/1365-2656.13600
  image: images/coomes_2022.jpg

- id: doi:10.1111/1365-2656.13551
  image: images/reichert_2021.jpg

- id: doi:10.1101/2021.04.28.441816
  image: images/reichert_2021b.png

- id: doi:10.1111/1365-2656.13428
  image: images/davidson_2021.jpg

- doi: doi:10.1038/s41598-020-77256-y
  image: images/problem_solving.png
  title: 'Diet induces parallel changes to the gut microbiota and problem solving performance in a wild bird'
  authors:
  - Gabrielle L. Davidson
  - Niamg Wiley
  - Amy C. Cooke
  - Crystal N. Johnson
  - Fiona Fouhy
  - Michael S Reichert
  - Ivan de la Hera
  - Jodie M. S. Crane
  - Ipek G Kulahci
  - R Paul Ross
  - Catherine Stanton
  - John L. Quinn
  link: https://www.nature.com/articles/s41598-020-77256-y
  publisher: Scientific Reports
  date: '2020-11-27'

- id: doi:10.1016/j.anbehav.2021.01.024
  image: images/cooke_2020.jpg

- id: doi:10.1101/2020.12.16.423008
  remove: true

- id: doi:10.1016/j.tree.2020.06.014
  image: images/davidson_2020b.png

- id: doi:10.1098/rsos.192107
  image: images/reichert_2020.jpg

- id: doi:10.1098/rstb.2017.0286
  image: images/davidson_2018.jpg

- id: doi:10.11646/zoosymposia.12.1.6
  image: images/helden_2018.jpg

- id: doi:10.1098/rsos.172218
  image: images/davidson_2018b.png

- id: doi:10.1098/rsbl.2016.0783
  image: images/davidson_2017b.jpg

- doi: doi:10.1038/srep40062
  image: images/davidson_2017.png
  title: 'The development of support intuitions and object causality in juvenile Eurasian jays (Garrulus glandarius)'
  authors:
  - Gabrielle L. Davidson
  - Rachael Miller
  - Elsa Loissel
  - Lucy G. Cheke
  - Nicola S. Clayton
  link: https://www.nature.com/articles/srep40062
  publisher: Scientific Reports
  date: '2017-02-24'

- id: doi:10.1016/j.anbehav.2015.07.010
  image: images/davidson_2015.jpg

- id: doi:10.1098/rsbl.2013.1077
  image: images/davidson_2014.jpg

- id: doi:10.1016/j.anbehav.2013.10.024
  image: images/davidson_2013.jpg

- id: doi:10.1136/jnnp-2012-302451
  image: images/murphy_2012.jpg

- id: doi:10.1007/s00415-011-6397-y
  image: images/davidson_2012.png

- id: doi:10.1111/j.1529-8027.2012.00400.x
  image: images/rossor.jpg

- id: doi:10.1136/jnnp.2010.228965
  image: images/murphy_2010.jpg